# Mind the Gap — Mind the Gap (dark)
# https://github.com/danfry1/mind-the-gap

[colors-dark]
cursor = 0c1628 E32017

foreground = d8dce8
background = 0c1628
selection-foreground = d8dce8
selection-background = 1e2844
urls = 0098D4

regular0 = 424C60
regular1 = E32017
regular2 = 00B850
regular3 = FFD300
regular4 = 5088D0
regular5 = D060A8
regular6 = 00A4A7
regular7 = A0A5A9

bright0 = 586878
bright1 = D89850
bright2 = 50D880
bright3 = EE7C0E
bright4 = 0098D4
bright5 = 9B70D8
bright6 = 80D0C0
bright7 = d8dce8
